booktime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView, DetailView

from main import views, models, forms

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('about-us/', TemplateView.as_view(template_name="about_us.html"), name="about_us"),
    path('contact-us/', views.ContactUsView.as_view(), name="contact_us"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name="login.html",
            form_class=forms.AuthenticationForm,
        ),
        name="login",
    ),
    path('address/', views.AddressListView.as_view(), name='address_list'),
    path('address/create/', views.AddressCreateView.as_view(), name='address_create'),
    path('address/<int:pk>/', views.AddressUpdateView.as_view(), name='address_update'),
    path('address/<int:pk>/delete', views.AddressDeleteView.as_view(), name='address_delete'),
    path('product/<slug:slug>/', DetailView.as_view(model=models.Product), name='product'),
    path('products/<slug:tag>/', views.ProductListView.as_view(), name="products"),
    path('add_to_basket/', views.add_to_basket, name='add_to_basket'),
    path('basket/', views.manage_basket, name="basket"),
    path('order/done', TemplateView.as_view(template_name='order_done.html'), name='checkout_done',),
    path('order/address_select', views.AddressSelectionView.as_view(), name='address_select',)
]

main/models.py
import logging

from django.db import models
from django.contrib.auth.models import (AbstractUser, BaseUserManager)
from django.core.validators import MinValueValidator

from . import exceptions

# Create your models here.

logger = logging.getLogger(__name__)


class UserManager(BaseUserManager):
    use_in_migration = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(
                "Superuser must have is_staff=True"
            )

        if extra_fields.get("is_superuser") is not True:
            raise ValueError(
                "Superuser must have is_superuser=True"
            )

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField('email address', unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()


class Address(models.Model):
    SUPPORTED_COUNTIES = (
        ("uk", "United Kingdom"),
        ("us", "United States of America"),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    address1 = models.CharField("Address line 1", max_length=60)
    address2 = models.CharField("Address line 2", max_length=60, blank=True)
    zip_code = models.CharField("Zip / Postal code", max_length=12)
    city = models.CharField(max_length=60)
    country = models.CharField(max_length=3, choices=SUPPORTED_COUNTIES)

    def __str__(self):
        return ", ".join(
            [
                self.name,
                self.address1,
                self.address2,
                self.zip_code,
                self.city,
                self.country
            ]
        )


class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class ProductTag(models.Model):
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    objects = ProductTagManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug,)


class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class Product(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(ProductTag, blank=True)

    objects = ActiveManager()

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product-images")
    thumbnail = models.ImageField(upload_to="product-thumbnails", null=True)


class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = (
        (OPEN, "Open"), (SUBMITTED, "Submitted")
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    status = models.IntegerField(choices=STATUSES, default=OPEN)

    def is_empty(self):
        return self.basketline_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())

    def create_order(self, billing_address, shipping_address):
        if not self.user:
            raise exceptions.BasketException(
                "Cannot create order without user"
            )

        logger.info(
            "Creating order for basket id=%d"
            ", shipping_address_id=%d, billing_address_id=%d",
            self.id,
            shipping_address.id,
            billing_address.id,
        )

        order_data = {
            "user": self.user,
            "billing_name": billing_address.name,
            "billing_address1": billing_address.address1,
            "billing_address2": billing_address.address2,
            "billing_zip_code": billing_address.zip_code,
            "billing_city": billing_address.city,
            "billing_country": billing_address.country,
            "shipping_name": shipping_address.name,
            "shipping_address1": shipping_address.address1,
            "shipping_address2": shipping_address.address2,
            "shipping_zip_code": shipping_address.zip_code,
            "shipping_city": shipping_address.city,
            "shipping_country": shipping_address.country,
        }

        order = Order.objects.create(**order_data)
        c = 0
        for line in self.basketline_set.all():
            for item in range(line.quantity):
                order_line_data = {
                    "order": order,
                    "product": line.product,
                }
                order_line = OrderLine.objects.create(
                    **order_line_data
                )
                c += 1
        logger.info("Created order with id=%d and lines_count=%d", order.id, c,)
        self.status = Basket.SUBMITTED
        self.save()
        return order


class BasketLine(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])


class Order(models.Model):
    NEW = 10
    PAID = 20
    DONE = 30
    STATUSES = (
        (NEW, "New"), (PAID, "Paid"), (DONE, "Done")
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUSES, default=NEW)

    billing_name = models.CharField(max_length=60)
    billing_address1 = models.CharField(max_length=60)
    billing_address2 = models.CharField(max_length=60, blank=True)

    billing_zip_code = models.CharField(max_length=12)
    billing_city = models.CharField(max_length=60)
    billing_country = models.CharField(max_length=3)

    shipping_name = models.CharField(max_length=60)
    shipping_address1 = models.CharField(max_length=60)
    shipping_address2 = models.CharField(max_length=60, blank=True)

    shipping_zip_code = models.CharField(max_length=12)
    shipping_city = models.CharField(max_length=60)
    shipping_country = models.CharField(max_length=3)

    date_updated = models.DateTimeField(auto_now=True)
    date_added = models.DateTimeField(auto_now=True)


class OrderLine(models.Model):
    NEW = 10
    PROCESSING = 20
    SENT = 30
    CANCELLED = 40

    STATUSES = (
        (NEW, "New"),
        (PROCESSING, "Processing"),
        (SENT, "Sent"),
        (CANCELLED, "Cancelled")
    )

    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="lines")
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    status = models.IntegerField(choices=STATUSES, default=NEW)

main/forms.py
import logging

from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import (
    UserCreationForm as DjangoUserCreationForm
)
from django.contrib.auth.forms import UsernameField
from django.core.mail import send_mail
from django.forms import inlineformset_factory

from . import models, widgets

logger = logging.getLogger(__name__)


class AuthenticationForm(forms.Form):

    email = forms.EmailField()
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            self.user = authenticate(self.request, email=email, password=password)
            if self.user is None:
                raise forms.ValidationError("Invalid email/password combination")
            logger.info("Authentication successful for email=%s", email)
            return self.cleaned_data

    def get_user(self):
        return self.user


class UserCreationForm(DjangoUserCreationForm):

    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields = ("email",)
        field_classes = {"email": UsernameField}

    def send_mail(self):
        logger.info(
            "Sending signup email for email=%s",
            self.cleaned_data["email"],
        )
        message = "Welcome {}".format(self.cleaned_data["email"])
        send_mail(
            "Welcome to BookTime",
            message,
            "site@booktime.domain",
            [self.cleaned_data["email"]],
            fail_silently=True,
        )


class ContactForm(forms.Form):

    name = forms.CharField(label='Your name', max_length=100)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )
        send_mail(
            "Site message",
            message,
            "site@booktime.domain",
            ["customerservice@booktime.domain"],
            fail_silently=False,
        )


BasketLineFormSet = inlineformset_factory(
    models.Basket,
    models.BasketLine,
    fields=("quantity",),
    extra=0,
    widgets={"quantity": widgets.PlusMinusNumberInput()},
)


class AddressSelectionForm(forms.Form):
    billing_address = forms.ModelChoiceField(queryset=None)
    shipping_address = forms.ModelChoiceField(queryset=None)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        queryset = models.Address.objects.filter(user=user)
        self.fields['billing_address'].queryset = queryset
        self.fields['shipping_address'].queryset = queryset

main/views.py
import logging

from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from main import forms, models


# Create your views here.

logger = logging.getLogger(__name__)


class AddressListView(LoginRequiredMixin, ListView):
    model = models.Address

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressCreateView(LoginRequiredMixin, CreateView):
    model = models.Address

    fields = [
        "name",
        "address1",
        "address2",
        "zip_code",
        "city",
        "country"
    ]
    success_url = reverse_lazy("address_list")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Address
    fields = [
        "name",
        "address1",
        "address2",
        "zip_code",
        "city",
        "country"
    ]
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Address
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class SignupView(FormView):
    template_name = "signup.html"
    form_class = forms.UserCreationForm

    def get_success_url(self):
        redirect_to = self.request.GET.get("next", "/")
        return redirect_to

    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()

        email = form.cleaned_data.get("email")
        raw_password = form.cleaned_data.get("password1")
        logger.info(
            "New signup for email=%s through signup view", email
        )

        # user = authenticate(email=email, raw_password=raw_password)
        logger.info("user is ", user)

        login(self.request, user)

        form.send_mail()

        messages.info(
            self.request, "You signed up successfully."
        )

        return response


class ProductListView(ListView):
    template_name = "main/product_list.html"
    paginate_by = 4

    def get_queryset(self):
        tag = self.kwargs['tag']
        self.tag = None

        if tag != "all":
            self.tag = get_object_or_404(models.ProductTag, slug=tag)

        if self.tag:
            products = models.Product.objects.active().filter(tags=self.tag)
        else:
            products = models.Product.objects.active()

        return products.order_by("name")


class ContactUsView(FormView):
    template_name = "contact_form.html"
    form_class = forms.ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)


def add_to_basket(request):
    product = get_object_or_404(
        models.Product, pk=request.GET.get("product_id")
    )
    basket = request.basket
    if not request.basket:
        if request.user.is_authenticated:
            user = request.user
        else:
            user = None
        basket = models.Basket.objects.create(user=user)
        request.session["basket_id"] = basket.id

    basketline, created = models.BasketLine.objects.get_or_create(
        basket=basket, product=product
    )
    if not created:
        basketline.quantity += 1
        basketline.save()
    return HttpResponseRedirect(
        reverse("product", args=(product.slug,))
    )


def manage_basket(request):
    if not request.basket:
        return render(request, "basket.html", {"formset": None})

    if request.method == "POST":
        formset = forms.BasketLineFormSet(
            request.POST, instance=request.basket
        )
        if formset.is_valid():
            formset.save()
    else:
        formset = forms.BasketLineFormSet(instance=request.basket)

    if request.basket.is_empty():
        return render(request, "basket.html", {"formset": None})

    return render(request, "basket.html", {"formset": formset})


class AddressSelectionView(LoginRequiredMixin, FormView):
    template_name = "address_select.html"
    form_class = forms.AddressSelectionForm
    success_url = reverse_lazy('checkout_done')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        del self.request.session['basket_id']
        basket = self.request.basket
        basket.create_order(
            form.cleaned_data['billing_address'],
            form.cleaned_data['shipping_address']
        )
        return super().form_valid(form)

main/templates/about_us.html
{% extends "base.html" %}

{% block content %}
    <h2>About us</h2>
    <p>BookTime is a company that sells books online.</p>
{% endblock content %}

main/templates/address_select.html
{% extends "base.html" %}

{% block content %}
    <h2>Select the billing/shipping addresses</h2>
    <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="btn btn-primary" href="{% url "address_create" %}">Add a new one</a>
    </form>
{% endblock content %}

main/templates/base.html
{% load static %}
<!doc type html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
        <title>BookTime</title>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">BookTime</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% if request.path == "/" %} active {% endif %}">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item {% if request.path == "/about-us/" %} active {% endif %}">
                        <a class="nav-link" href="/about-us/">About us</a>
                    </li>
                    <li class="nav-item {% if request.path == "/products/all" %} active {% endif %}">
                        <a class="nav-link" href="/products/all">Products</a>
                    </li>
                    <li class="nav-item {% if request.path == "/contact-us" %} active {% endif %}">
                        <a class="nav-link" href="/contact-us">Contact us</a>
                    </li>
                    <li class="nav-item {% if request.path == '/login/' %} active {% endif %}">
                        <a class="nav-link" href="/login/">Login</a>
                    </li>
                    <li class="nav-item {% if request.path == "/signup" %} active {% endif %}">
                        <a class="nav-link" href="/signup">Signup</a>
                    </li>
                </ul>
            </div>
        </nav>

        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}

        {% if request.basket %}
            <div>
                {{ request.basket.count }}
                items in basket
            </div>
        {% endif %}

        {% block content %}
        {% endblock content %}

        <script src="{% static "js/jquery.min.js" %}"></script>
        <script src="{% static "js/popper.min.js" %}"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        {% block js %}
        {% endblock js %}
    </body>
</html>

main/templates/basket.html
{% extends "base.html" %}

{% block content %}
    <h2>Basket</h2>
    {% if formset %}
        <p>You can adjust the quantities below.</p>
        <form method="POST">
            {% csrf_token %}
            {{ formset.management_form }}
            {% for form in formset %}
                <p>
                    {{ form.instance.product.name }}
                    {{ form }}
                </p>
            {% endfor %}
            <button type="submit" class="btn btn-default">Update basket</button>
            {% if user.is_authenticated %}
                <a href="{% url "address_select" %}"
                   class="btn btn-primary">Place order</a>
            {% else %}
                <a href="{% url "signup" %}?next={% url "address_select" %}"
                   class="btn btn-primary">Signup</a>
                <a href="{% url "login" %}?next={% url "address_select" %}"
                   class="btn btn-primary">Login</a>
            {% endif %}
        </form>
        {% else %}
        <p> You have no items in the basket.</p>
    {% endif %}
{% endblock content %}
{% block js %}
    {% if formset %}
        {{ formset.media }}
    {% endif %}
{% endblock js %}

main/templates/contact_form.html
{%  extends "base.html" %}

{% block content %}
    <h2>Contact us</h2>
    <p>Please fill the form below to contact us</p>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.name.label_tag }}
            <input type="text"
                   class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                   id="id_name"
                   name="name"
                   placeholder="Your name"
                   value="{{ form.name.value|default:"" }}" >
            {% if form.name.errors %}
                <div class="invalid-feedback">
                    {{ form.name.erros }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{  form.message.label_tag }}
            <textarea
                    class="form-control {% if form.message.errors %}is-invalid{% endif %}"
                    id="id_message"
                    name="message"
                    rows="3">
                {{ form.message.value|default:"" }}
            </textarea>
            {% if form.message.errors %}
                <div class="invalid-feedback">
                    {{ form.message.erros }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

main/templates/home.html
{% extends "base.html" %}
{% block content %}
    <h2>Home</h2>
    <p>this will be the content of home.</p>
{% endblock content %}

main/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h2>Login</h2>
    <p>Please fill the form below.</p>
    <form method="POST">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="form-group">
            {{ form.email.label_tag }}
            <input
                type="email"
                class="form-control {% if form.email.errors %} is-invalid {% endif %}"
                id="id_email"
                name="email"
                placeholder="Your email"
                value="{{ form.email.value|default:"" }}">
            {% if form.email.errors %}
                <div class="invalid-feedback">
                    {{ form.email.errors }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label_tag }}
            <input
                type="password"
                class="form-control {% if form.password.errors %}is-invalid{% endif %}"
                id="id_password"
                name="password"
                value="{{ form.password.value|default:"" }}">
            {% if form.email.errors %}
                <div class="invalid-feedback">
                    {{ form.password.errors }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

main/templates/order_done.html
{% extends "base.html" %}
{% block content %}
    <p>Thanks for your order.</p>
{% endblock content %}

main/templates/signup.html
{% extends "base.html" %}

{% block content %}
    <h2>Signup</h2>
    <p>Pleas fill the form below.</p>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.email.label_tag }}
            <input type="email"
                   class="form-control {% if form.email.errors %} is-invalid {% endif %}"
                   id="email"
                   name="email"
                   placeholder="Your email"
                   value="{{ form.email.value|default:""}}">
            {% if form.email.erros %}
                <div class="invalid-feedback">
                    {{ form.email.errors }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password1.label_tag }}
            <input type="password"
                   class="form-control {% if form.password1.errors %} is-invalid {% endif %}"
                   id="id_password1"
                   name="password1"
                   value="{{ form.password1.value|default:""}}">
            {% if form.password1.errors %}
                <div class="invalid-feedback">
                    {{ form.password1.errors }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password12.label_tag }}
            <input type="password"
                   class="form-control {% if form.password2.errors %} is-invalid {% endif %}"
                   id="id_password2"
                   name="password2"
                   value="{{ form.password2.value|default:""}}">
            {% if form.password2.errors %}
                <div class="invalid-feedback">
                    {{ form.password2.errors }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock content %}